# Identity & Security Stack Fragment
# This is a fragment (no productVersion) - only loadable via include
# Contains: Identity Access, PolicyServer Authorization

metadata:
  name: Identity & Security
  description: Identity Provider and Authorization services
  category: Security
  tags:
    - identity
    - authorization
    - policyserver
    - authentication

variables:
  # ===========================================
  # Identity & Security
  # ===========================================
  IDENTITY_ACCESS_CERT_PATH:
    label: Certificate Path
    description: Path to the identity API certificate
    type: String
    default: /etc/ssl/certs/identity-api.pfx
    group: Security
    order: 1

  IDENTITY_ACCESS_CERT_PASSWORD:
    label: Certificate Password
    description: Password for the identity certificate
    type: Password
    default: "P@ssw0rd!"
    group: Security
    order: 2

  # ===========================================
  # Email Configuration
  # ===========================================
  MAIL_SERVER:
    label: Mail Server
    description: SMTP server hostname
    type: String
    default: host.docker.internal
    group: Email
    order: 1

  MAIL_PORT:
    label: Mail Port
    description: SMTP server port
    type: Port
    default: "25"
    group: Email
    order: 2

  MAIL_SENDER_NAME:
    label: Sender Name
    description: Display name for sent emails
    type: String
    default: ams.project
    group: Email
    order: 3

  MAIL_SENDER:
    label: Sender Address
    description: Email address for sent emails
    type: String
    default: noreply@host.docker.internal
    pattern: "^[^@]+@[^@]+$"
    patternError: Must be a valid email address
    group: Email
    order: 4

  MAIL_PASSWORD:
    label: Mail Password
    description: SMTP authentication password (if required)
    type: Password
    default: ""
    group: Email
    order: 5

  MAIL_IS_AUTHENTICATION_REQUIRED:
    label: Authentication Required
    description: Whether SMTP authentication is required
    type: Boolean
    default: "false"
    group: Email
    order: 6

services:
  # ===========================================
  # AUTHORIZATION (PolicyServer)
  # ===========================================
  policyserver:
    image: amssolution/policyserver:linux-v2.4.0
    restart: always
    environment:
      ConnectionStrings__ams: ${AMS_DB}
      ConnectionStrings__IdentityAccess: ${IDENTITY_ACCESS_DB}
      Serilog__LogstashUrl: http://${AMS_PROJECT_EXTERNAL_DNS_NAME_OR_IP}:8080
      Serilog__MinimumLevel: ${MIN_LOG_LEVEL}

  policyserver-manager-api:
    image: amssolution/policyserver.manager.api:linux-v2.4.0
    restart: always
    ports:
      - "7612:80"
    environment:
      ConnectionStrings__ams: ${AMS_DB}
      ConnectionStrings__IdentityAccess: ${IDENTITY_ACCESS_DB}
      CultureCode: ${CULTURE_CODE}
      Serilog__LogstashUrl: http://${AMS_PROJECT_EXTERNAL_DNS_NAME_OR_IP}:8080
      Serilog__MinimumLevel: ${MIN_LOG_LEVEL}

  policyserver-manager-userselector-api:
    image: amssolution/policyserver.manager.userselector.api:linux-v2.4.0
    restart: always
    ports:
      - "7613:80"
    environment:
      ConnectionStrings__IdentityAccess: ${IDENTITY_ACCESS_DB}
      Serilog__LogstashUrl: http://${AMS_PROJECT_EXTERNAL_DNS_NAME_OR_IP}:8080
      Serilog__MinimumLevel: ${MIN_LOG_LEVEL}

  # ===========================================
  # IDENTITY ACCESS
  # ===========================================
  identity-api:
    image: amssolution/identityaccess.identityserver:linux-v2.4.0
    restart: always
    ports:
      - "7614:80"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://0.0.0.0:80
      ConnectionStrings__IdentityAccess: ${IDENTITY_ACCESS_DB}
      ServiceBusTimeToWaitBeforeTriggeringCircuitBreaker: ${SERVICE_BUS_TIME_TO_WAIT_BEFORE_TRIGGERING_CIRCUIT_BREAKER}
      ExitOnCriticalError: ${EXIT_ON_CRITICAL_ERROR}
      CultureCode: ${CULTURE_CODE}
      IdentityServerUrl: http://${AMS_PROJECT_EXTERNAL_DNS_NAME_OR_IP}:7614
      Serilog__LogstashUrl: http://${AMS_PROJECT_EXTERNAL_DNS_NAME_OR_IP}:8080
      Serilog__MinimumLevel: ${MIN_LOG_LEVEL}
      CertificatePath: ${IDENTITY_ACCESS_CERT_PATH}
      CertificatePassword: ${IDENTITY_ACCESS_CERT_PASSWORD}
      SERVICE_BUS_CATALOG: ${SERVICE_BUS_CATALOG}
    volumes:
      - profilePictures:/app/wwwroot/picture
      - ./certs:/etc/ssl/certs:ro

  adminportal:
    image: amssolution/identityaccess.adminportal:linux-v2.4.0
    restart: always
    ports:
      - "7615:80"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://0.0.0.0:80
      ConnectionStrings__IdentityAccess: ${IDENTITY_ACCESS_DB}
      ServiceBusTimeToWaitBeforeTriggeringCircuitBreaker: ${SERVICE_BUS_TIME_TO_WAIT_BEFORE_TRIGGERING_CIRCUIT_BREAKER}
      ExitOnCriticalError: ${EXIT_ON_CRITICAL_ERROR}
      CultureCode: ${CULTURE_CODE}
      IdentityServerUrl: http://identity-api
      Serilog__LogstashUrl: http://${AMS_PROJECT_EXTERNAL_DNS_NAME_OR_IP}:8080
      Serilog__MinimumLevel: ${MIN_LOG_LEVEL}
      SERVICE_BUS_CATALOG: ${SERVICE_BUS_CATALOG}

  identityaccess-clienthub:
    image: amssolution/identityaccess.clienthub:linux-v2.4.0
    restart: always
    ports:
      - "7616:80"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://0.0.0.0:80
      ConnectionStrings__IdentityAccess: ${IDENTITY_ACCESS_DB}
      ServiceBusTimeToWaitBeforeTriggeringCircuitBreaker: ${SERVICE_BUS_TIME_TO_WAIT_BEFORE_TRIGGERING_CIRCUIT_BREAKER}
      ExitOnCriticalError: ${EXIT_ON_CRITICAL_ERROR}
      Serilog__LogstashUrl: http://${AMS_PROJECT_EXTERNAL_DNS_NAME_OR_IP}:8080
      Serilog__MinimumLevel: ${MIN_LOG_LEVEL}
      SERVICE_BUS_CATALOG: ${SERVICE_BUS_CATALOG}

  identityaccess-emailsender:
    image: amssolution/identityaccess.emailsender:linux-v2.4.0
    restart: always
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://0.0.0.0:80
      ConnectionStrings__IdentityAccess: ${IDENTITY_ACCESS_DB}
      ServiceBusTimeToWaitBeforeTriggeringCircuitBreaker: ${SERVICE_BUS_TIME_TO_WAIT_BEFORE_TRIGGERING_CIRCUIT_BREAKER}
      ExitOnCriticalError: ${EXIT_ON_CRITICAL_ERROR}
      CultureCode: ${CULTURE_CODE}
      EmailSettings__MailServer: ${MAIL_SERVER}
      EmailSettings__Port: ${MAIL_PORT}
      EmailSettings__SenderName: ${MAIL_SENDER_NAME}
      EmailSettings__Sender: ${MAIL_SENDER}
      EmailSettings__Password: ${MAIL_PASSWORD}
      EmailSettings__IsAuthenticationRequired: ${MAIL_IS_AUTHENTICATION_REQUIRED}
      Serilog__LogstashUrl: http://${AMS_PROJECT_EXTERNAL_DNS_NAME_OR_IP}:8080
      Serilog__MinimumLevel: ${MIN_LOG_LEVEL}
      SERVICE_BUS_CATALOG: ${SERVICE_BUS_CATALOG}
    volumes:
      - ./certs:/etc/ssl/certs

volumes:
  profilePictures: {}
