# Infrastructure Stack Fragment
# This is a fragment (no productVersion) - only loadable via include

metadata:
  name: Infrastructure
  description: Core infrastructure services (EventStore, Redis)
  category: Infrastructure
  tags:
    - eventstore
    - redis
    - cache

variables:
  EVENTSTORE_DB:
    label: EventStore Connection (TCP)
    description: EventStore TCP connection string
    type: String
    default: "tcp://admin:changeit@eventstore:1113"
    group: Infrastructure
    order: 1

  GRPC_EVENTSTORE_DB:
    label: EventStore Connection (gRPC)
    description: EventStore gRPC connection string for newer services
    type: String
    default: "esdb://admin:changeit@eventstore.db:2113?tls=false"
    group: Infrastructure
    order: 2

  REDIS_DB:
    label: Redis Connection
    description: Redis cache hostname
    type: String
    default: cachedata
    group: Infrastructure
    order: 3

services:
  eventstore:
    image: eventstore/eventstore:release-5.0.11
    restart: always
    init: true
    ports:
      - "2113:2113"
      - "1113:1113"
    volumes:
      - esdata:/var/lib/eventstore
      - esindex:/var/lib/eventstore-index

  eventstore.db:
    image: docker.eventstore.com/eventstore/eventstoredb-ee:latest
    restart: always
    init: true
    ports:
      - "2114:2113"
      - "1114:1113"
    environment:
      EVENTSTORE_CLUSTER_SIZE: "1"
      EVENTSTORE_RUN_PROJECTIONS: All
      EVENTSTORE_START_STANDARD_PROJECTIONS: "true"
      EVENTSTORE_NODE_PORT: "2113"
      EVENTSTORE_INSECURE: "true"
      EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP: "true"
    volumes:
      - eventstore-volume-data:/var/lib/eventstore
      - eventstore-volume-logs:/var/log/eventstore

  cachedata:
    image: redis:alpine
    restart: always
    command: redis-server --include /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
      - ./redis/data:/data

volumes:
  esdata: {}
  esindex: {}
  eventstore-volume-data: {}
  eventstore-volume-logs: {}
