// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ReadyStackGo.Infrastructure.DataAccess;

#nullable disable

namespace ReadyStackGo.Infrastructure.DataAccess.Migrations
{
    [DbContext(typeof(ReadyStackGoDbContext))]
    partial class ReadyStackGoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("ReadyStackGo.Domain.Deployment.Deployments.Deployment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("CancellationReason")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("CurrentPhase")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("DeployedBy")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EnvironmentId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("HealthCheckConfigs")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("HealthCheckConfigsJson");

                    b.Property<string>("InitContainerResults")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("InitContainerResultsJson");

                    b.Property<bool>("IsCancellationRequested")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastUpgradedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("MaintenanceObserverConfig")
                        .HasColumnType("TEXT")
                        .HasColumnName("MaintenanceObserverConfigJson");

                    b.Property<string>("MaintenanceTrigger")
                        .HasColumnType("TEXT")
                        .HasColumnName("MaintenanceTriggerJson");

                    b.Property<int>("OperationMode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PreviousVersion")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProgressMessage")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProgressPercentage")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("StackId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("StackName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("StackVersion")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UpgradeCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<string>("Variables")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("VariablesJson");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EnvironmentId");

                    b.HasIndex("Status");

                    b.ToTable("Deployments", (string)null);
                });

            modelBuilder.Entity("ReadyStackGo.Domain.Deployment.Environments.Environment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConnectionConfig")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("ConnectionConfigJson");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SshCredential")
                        .HasColumnType("TEXT")
                        .HasColumnName("SshCredentialJson");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("OrganizationId", "Name")
                        .IsUnique();

                    b.ToTable("Environments", (string)null);
                });

            modelBuilder.Entity("ReadyStackGo.Domain.Deployment.Environments.EnvironmentVariable", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EnvironmentId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEncrypted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EnvironmentId");

                    b.HasIndex("EnvironmentId", "Key")
                        .IsUnique();

                    b.ToTable("EnvironmentVariables", (string)null);
                });

            modelBuilder.Entity("ReadyStackGo.Domain.Deployment.Health.HealthSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Bus")
                        .HasColumnType("TEXT")
                        .HasColumnName("BusHealthJson");

                    b.Property<DateTime>("CapturedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrentVersion")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DeploymentId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EnvironmentId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Infra")
                        .HasColumnType("TEXT")
                        .HasColumnName("InfraHealthJson");

                    b.Property<int>("OperationMode")
                        .HasColumnType("INTEGER")
                        .HasColumnName("OperationMode");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Overall")
                        .HasColumnType("INTEGER")
                        .HasColumnName("OverallStatus");

                    b.Property<string>("Self")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("SelfHealthJson");

                    b.Property<string>("StackName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetVersion")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CapturedAtUtc");

                    b.HasIndex("DeploymentId");

                    b.HasIndex("EnvironmentId");

                    b.HasIndex("DeploymentId", "CapturedAtUtc");

                    b.ToTable("HealthSnapshots", (string)null);
                });

            modelBuilder.Entity("ReadyStackGo.Domain.Deployment.ProductDeployments.ProductDeployment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("ContinueOnError")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DeployedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeploymentName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EnvironmentId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastUpgradedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("MaintenanceObserverConfig")
                        .HasColumnType("TEXT")
                        .HasColumnName("MaintenanceObserverConfigJson");

                    b.Property<string>("MaintenanceTrigger")
                        .HasColumnType("TEXT")
                        .HasColumnName("MaintenanceTriggerJson");

                    b.Property<int>("OperationMode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PhaseHistory")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("PhaseHistoryJson");

                    b.Property<string>("PreviousVersion")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductDisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductGroupId")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductId")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductVersion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("SharedVariables")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("SharedVariablesJson");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UpgradeCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EnvironmentId");

                    b.HasIndex("ProductGroupId");

                    b.HasIndex("Status");

                    b.ToTable("ProductDeployments", (string)null);
                });

            modelBuilder.Entity("ReadyStackGo.Domain.Deployment.Registries.Registry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.Property<string>("_imagePatterns")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT")
                        .HasColumnName("ImagePatterns");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("OrganizationId", "IsDefault")
                        .HasFilter("[IsDefault] = 1");

                    b.HasIndex("OrganizationId", "Name")
                        .IsUnique();

                    b.ToTable("Registries", (string)null);
                });

            modelBuilder.Entity("ReadyStackGo.Domain.IdentityAccess.ApiKeys.ApiKey", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("EnvironmentId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("INTEGER");

                    b.Property<string>("KeyHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("KeyPrefix")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastUsedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("RevokedReason")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.Property<string>("_permissions")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT")
                        .HasColumnName("Permissions");

                    b.HasKey("Id");

                    b.HasIndex("KeyHash")
                        .IsUnique();

                    b.HasIndex("OrganizationId");

                    b.HasIndex("OrganizationId", "Name")
                        .IsUnique();

                    b.ToTable("ApiKeys", (string)null);
                });

            modelBuilder.Entity("ReadyStackGo.Domain.IdentityAccess.Organizations.Organization", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("Id");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("OwnerId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("OwnerId");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Organizations", (string)null);
                });

            modelBuilder.Entity("ReadyStackGo.Domain.IdentityAccess.Users.User", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("Id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("FailedLoginAttempts")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LockReason")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LockedUntil")
                        .HasColumnType("TEXT");

                    b.Property<bool>("MustChangePassword")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("PasswordChangedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("ReadyStackGo.Domain.StackManagement.Sources.StackSource", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FilePattern")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("GitBranch")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("GitPassword")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("GitSslVerify")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<string>("GitUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("GitUsername")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastSyncedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Path")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("RegistryPassword")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("RegistryUrl")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("RegistryUsername")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Repository")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("TagPattern")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Enabled");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("Type");

                    b.ToTable("StackSources", (string)null);
                });

            modelBuilder.Entity("ReadyStackGo.Domain.Deployment.Deployments.Deployment", b =>
                {
                    b.OwnsMany("ReadyStackGo.Domain.Deployment.Deployments.DeployedService", "Services", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("INTEGER");

                            b1.Property<string>("ContainerId")
                                .HasMaxLength(100)
                                .HasColumnType("TEXT");

                            b1.Property<string>("ContainerName")
                                .HasMaxLength(200)
                                .HasColumnType("TEXT");

                            b1.Property<Guid>("DeploymentId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Image")
                                .HasMaxLength(500)
                                .HasColumnType("TEXT");

                            b1.Property<string>("ServiceName")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("TEXT");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("TEXT");

                            b1.HasKey("Id");

                            b1.HasIndex("DeploymentId");

                            b1.ToTable("DeployedServices", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("DeploymentId");
                        });

                    b.OwnsMany("ReadyStackGo.Domain.Deployment.Deployments.DeploymentPhaseRecord", "PhaseHistory", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("INTEGER");

                            b1.Property<Guid>("DeploymentId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Message")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("TEXT");

                            b1.Property<int>("Phase")
                                .HasColumnType("INTEGER");

                            b1.Property<DateTime>("Timestamp")
                                .HasColumnType("TEXT");

                            b1.HasKey("Id");

                            b1.HasIndex("DeploymentId");

                            b1.ToTable("DeploymentPhaseHistory", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("DeploymentId");
                        });

                    b.Navigation("PhaseHistory");

                    b.Navigation("Services");
                });

            modelBuilder.Entity("ReadyStackGo.Domain.Deployment.ProductDeployments.ProductDeployment", b =>
                {
                    b.OwnsMany("ReadyStackGo.Domain.Deployment.ProductDeployments.ProductStackDeployment", "Stacks", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("INTEGER");

                            b1.Property<DateTime?>("CompletedAt")
                                .HasColumnType("TEXT");

                            b1.Property<Guid?>("DeploymentId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("DeploymentStackName")
                                .HasMaxLength(200)
                                .HasColumnType("TEXT");

                            b1.Property<string>("ErrorMessage")
                                .HasMaxLength(2000)
                                .HasColumnType("TEXT");

                            b1.Property<bool>("IsNewInUpgrade")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("INTEGER")
                                .HasDefaultValue(false);

                            b1.Property<int>("Order")
                                .HasColumnType("INTEGER");

                            b1.Property<Guid>("ProductDeploymentId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("ServiceCount")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("StackDisplayName")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("TEXT");

                            b1.Property<string>("StackId")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("TEXT");

                            b1.Property<string>("StackName")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("TEXT");

                            b1.Property<DateTime?>("StartedAt")
                                .HasColumnType("TEXT");

                            b1.Property<int>("Status")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Variables")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("VariablesJson");

                            b1.HasKey("Id");

                            b1.HasIndex("DeploymentId");

                            b1.HasIndex("ProductDeploymentId");

                            b1.ToTable("ProductStackDeployments", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ProductDeploymentId");
                        });

                    b.Navigation("Stacks");
                });

            modelBuilder.Entity("ReadyStackGo.Domain.IdentityAccess.Users.User", b =>
                {
                    b.OwnsOne("ReadyStackGo.Domain.IdentityAccess.Users.EmailAddress", "Email", b1 =>
                        {
                            b1.Property<string>("UserId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(254)
                                .HasColumnType("TEXT")
                                .HasColumnName("Email");

                            b1.HasKey("UserId");

                            b1.HasIndex("Value")
                                .IsUnique();

                            b1.ToTable("Users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.OwnsOne("ReadyStackGo.Domain.IdentityAccess.Users.Enablement", "Enablement", b1 =>
                        {
                            b1.Property<string>("UserId")
                                .HasColumnType("TEXT");

                            b1.Property<bool>("Enabled")
                                .HasColumnType("INTEGER")
                                .HasColumnName("Enabled");

                            b1.Property<DateTime?>("EndDate")
                                .HasColumnType("TEXT")
                                .HasColumnName("EnablementEndDate");

                            b1.Property<DateTime?>("StartDate")
                                .HasColumnType("TEXT")
                                .HasColumnName("EnablementStartDate");

                            b1.HasKey("UserId");

                            b1.ToTable("Users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.OwnsOne("ReadyStackGo.Domain.IdentityAccess.Users.HashedPassword", "Password", b1 =>
                        {
                            b1.Property<string>("UserId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Hash")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("TEXT")
                                .HasColumnName("PasswordHash");

                            b1.HasKey("UserId");

                            b1.ToTable("Users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.OwnsMany("ReadyStackGo.Domain.IdentityAccess.Users.RoleAssignment", "RoleAssignments", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("TEXT");

                            b1.Property<DateTime>("AssignedAt")
                                .HasColumnType("TEXT")
                                .HasColumnName("AssignedAt");

                            b1.Property<string>("RoleId")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("TEXT")
                                .HasColumnName("RoleId");

                            b1.Property<string>("ScopeId")
                                .HasMaxLength(36)
                                .HasColumnType("TEXT")
                                .HasColumnName("ScopeId");

                            b1.Property<int>("ScopeType")
                                .HasColumnType("INTEGER")
                                .HasColumnName("ScopeType");

                            b1.Property<string>("UserId")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.HasKey("Id");

                            b1.HasIndex("UserId", "RoleId", "ScopeType", "ScopeId")
                                .IsUnique();

                            b1.ToTable("UserRoles", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.Navigation("Email")
                        .IsRequired();

                    b.Navigation("Enablement")
                        .IsRequired();

                    b.Navigation("Password")
                        .IsRequired();

                    b.Navigation("RoleAssignments");
                });
#pragma warning restore 612, 618
        }
    }
}
