# Variable Showcase Stack - Demonstrates all RSGo Variable Types
# This stack is used for testing and documentation purposes

metadata:
  name: Variable Showcase
  description: Demonstrates all available variable types in RSGo Manifest Format
  productVersion: "1.0.0"
  category: Examples
  tags:
    - example
    - showcase
    - testing

variables:
  # String Type
  APP_NAME:
    label: Application Name
    description: The name of your application
    type: String
    default: MyApp
    placeholder: Enter app name
    group: General
    order: 1

  # Number Type
  MAX_CONNECTIONS:
    label: Max Connections
    description: Maximum number of database connections
    type: Number
    default: "100"
    min: 1
    max: 1000
    group: Performance
    order: 1

  # Boolean Type
  ENABLE_DEBUG:
    label: Enable Debug Mode
    description: Enable detailed logging and debugging
    type: Boolean
    default: "false"
    group: General
    order: 2

  # Password Type
  ADMIN_PASSWORD:
    label: Admin Password
    description: Password for the admin user
    type: Password
    required: true
    placeholder: Enter secure password
    group: Security
    order: 1

  # Port Type
  HTTP_PORT:
    label: HTTP Port
    description: Port for HTTP traffic
    type: Port
    default: "8080"
    min: 1
    max: 65535
    group: Network
    order: 1

  HTTPS_PORT:
    label: HTTPS Port
    description: Port for HTTPS traffic
    type: Port
    default: "8443"
    group: Network
    order: 2

  # Select Type
  ENVIRONMENT:
    label: Environment
    description: Deployment environment
    type: Select
    default: development
    options:
      - value: development
        label: Development
        description: Local development environment
      - value: staging
        label: Staging
        description: Pre-production testing environment
      - value: production
        label: Production
        description: Live production environment
    group: General
    order: 3

  # URL Type
  API_ENDPOINT:
    label: API Endpoint
    description: External API endpoint URL
    type: Url
    default: "https://api.example.com"
    placeholder: "https://..."
    group: External Services
    order: 1

  # Email Type
  ADMIN_EMAIL:
    label: Admin Email
    description: Administrator email address for notifications
    type: Email
    default: admin@example.com
    placeholder: admin@yourdomain.com
    group: Notifications
    order: 1

  # Path Type
  DATA_PATH:
    label: Data Path
    description: Path for data storage
    type: Path
    default: /data
    group: Storage
    order: 1

  # MultiLine Type
  SSL_CERTIFICATE:
    label: SSL Certificate
    description: PEM-encoded SSL certificate
    type: MultiLine
    placeholder: |
      -----BEGIN CERTIFICATE-----
      ...
      -----END CERTIFICATE-----
    group: Security
    order: 2

  # SqlServerConnectionString Type
  SQLSERVER_CONNECTION:
    label: SQL Server Connection
    description: Connection string for SQL Server database
    type: SqlServerConnectionString
    default: "Server=localhost;Database=mydb;User Id=sa;Password=YourPassword123!;TrustServerCertificate=true;"
    group: Database
    order: 1

  # PostgresConnectionString Type
  POSTGRES_CONNECTION:
    label: PostgreSQL Connection
    description: Connection string for PostgreSQL database
    type: PostgresConnectionString
    default: "Host=localhost;Database=mydb;Username=postgres;Password=yourpassword"
    group: Database
    order: 2

  # MongoConnectionString Type
  MONGODB_CONNECTION:
    label: MongoDB Connection
    description: Connection string for MongoDB database
    type: MongoConnectionString
    default: "mongodb://localhost:27017/mydb"
    group: Database
    order: 3

  # MySqlConnectionString Type
  MYSQL_CONNECTION:
    label: MySQL Connection
    description: Connection string for MySQL database
    type: MySqlConnectionString
    default: "Server=localhost;Database=mydb;Uid=root;Pwd=yourpassword;"
    group: Database
    order: 4

  # String with Pattern validation
  VERSION_TAG:
    label: Version Tag
    description: Semantic version tag (e.g., v1.0.0)
    type: String
    default: v1.0.0
    pattern: "^v\\d+\\.\\d+\\.\\d+$"
    patternError: Version must match format v#.#.# (e.g., v1.0.0)
    group: Versions
    order: 1

services:
  showcase-app:
    image: nginx:alpine
    ports:
      - "${HTTP_PORT}:80"
      - "${HTTPS_PORT}:443"
    environment:
      APP_NAME: ${APP_NAME}
      DEBUG: ${ENABLE_DEBUG}
      ENVIRONMENT: ${ENVIRONMENT}
      API_ENDPOINT: ${API_ENDPOINT}
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      SQLSERVER_CONNECTION: ${SQLSERVER_CONNECTION}
      POSTGRES_CONNECTION: ${POSTGRES_CONNECTION}
      MONGODB_CONNECTION: ${MONGODB_CONNECTION}
      MYSQL_CONNECTION: ${MYSQL_CONNECTION}
      VERSION_TAG: ${VERSION_TAG}
    volumes:
      - ${DATA_PATH}:/data
    restart: unless-stopped

volumes:
  data: {}
