# Whoami Stack - RSGo Manifest Format
# Simple HTTP service that returns container info - useful for testing

metadata:
  name: Whoami
  description: Simple HTTP service that returns container info - useful for testing
  productVersion: "1.0.0"
  category: Testing
  tags:
    - whoami
    - testing
    - debug

variables:
  WHOAMI_PORT:
    label: Whoami Port
    description: Port to access the whoami service
    type: Port
    default: "8081"
    group: Network
    order: 1

  INSTANCE_NAME:
    label: Instance Name
    description: Name displayed by the whoami service
    type: String
    default: whoami
    group: General
    order: 1

services:
  whoami:
    image: traefik/whoami:latest
    ports:
      - "${WHOAMI_PORT}:80"
    environment:
      WHOAMI_NAME: ${INSTANCE_NAME}
    healthCheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:80/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      startPeriod: 10s
