# E2E Platform - Backend Stack

metadata:
  name: Backend

variables:
  BACKEND_PORT:
    label: Backend Port
    description: Port for the backend service
    type: Port
    default: "8092"
    group: Network
    order: 1

  BACKEND_NAME:
    label: Backend Name
    description: Name displayed by the backend service
    type: String
    default: e2e-backend
    group: General
    order: 2

services:
  backend:
    image: traefik/whoami:v1.11
    ports:
      - "${BACKEND_PORT}:80"
    environment:
      WHOAMI_NAME: ${BACKEND_NAME}
      LOG_LEVEL: ${LOG_LEVEL}
